# Autogenerated by autotester

require 'rails_helper'

FactoryBot.define do
  factory :account_user do
    association :account
    association :user

    trait :with_created_timestamp do
      created_at { Time.current }
    end

    trait :with_updated_timestamp do
      updated_at { Time.current }
    end
  end
end
