# Autogenerated by autotester

FactoryBot.define do
  factory :account do
    sequence(:name) { |n| "Account #{n}" }
    association :owner, factory: :user

    after(:create) do |account|
      # Creating associated records for a well-rounded account
      create_list(:account_user, 3, account: account)
      create_list(:cluster, 2, account: account)
    end

    trait :with_projects_and_services do
      after(:create) do |account|
        account.clusters.each do |cluster|
          create_list(:project, 2, cluster: cluster)
          cluster.projects.each do |project|
            create_list(:service, 2, project: project)
          end
        end
      end
    end

    trait :with_add_ons do
      after(:create) do |account|
        account.clusters.each do |cluster|
          create_list(:add_on, 2, cluster: cluster)
        end
      end
    end
  end
end
