# Autogenerated by autotester

# spec/factories/add_ons.rb

FactoryBot.define do
  factory :add_on do
    association :cluster

    sequence(:name) { |n| "addon-#{n}" }
    chart_type { "helm_chart" }
    status { :installing }
    metadata { { "package_details" => "some details", "repository" => "http://example.com/repo" } }
    values { { "key" => "value" } }

    trait :installed do
      status { :installed }
    end

    trait :uninstalling do
      status { :uninstalling }
    end

    trait :failed do
      status { :failed }
    end

    trait :custom_chart_type do
      chart_type { "custom_chart" }
    end

    trait :with_additional_metadata do
      metadata { { "package_details" => "some details", "repository" => "http://example.com/repo", "extra" => "data" } }
    end
  end
end
