# Autogenerated by autotester

require 'rails_helper'

FactoryBot.define do
  factory :announcement do
    name { "Announcement #{Faker::Lorem.word}" }
    description { Faker::Lorem.paragraph }
    published_at { Time.zone.now }
    
    trait :new do
      announcement_type { 'new' }
    end

    trait :fix do
      announcement_type { 'fix' }
    end

    trait :update do
      announcement_type { 'update' }
    end

    factory :new_announcement, traits: [:new]
    factory :fix_announcement, traits: [:fix]
    factory :update_announcement, traits: [:update]
  end
end
