# Autogenerated by autotester

FactoryBot.define do
  factory :build do
    commit_message { "Initial commit" }
    commit_sha { SecureRandom.hex(20) }
    git_sha { SecureRandom.hex(20) }
    repository_url { "https://github.com/example/repo.git" }
    status { :in_progress }
    association :project

    trait :completed do
      status { :completed }
    end

    trait :failed do
      status { :failed }
    end

    trait :with_specific_commit do
      commit_message { "Fix bug in authentication" }
      commit_sha { "a1b2c3d4e5f6g7h8i9j0" }
    end

    trait :with_deployment do
      after(:create) do |build|
        create(:deployment, build: build)
      end
    end
  end
end
