# Autogenerated by autotester

require 'rails_helper'

FactoryBot.define do
  factory :cluster do
    association :account
    
    sequence(:name) { |n| "cluster-#{n}" }
    kubeconfig { { "apiVersion" => "v1", "clusters" => [], "contexts" => [], "current-context" => "", "kind" => "Config", "preferences" => {}, "users" => [] } }
    cluster_type { :k8s }
    status { :initializing }

    trait :installing do
      status { :installing }
    end

    trait :running do
      status { :running }
    end

    trait :failed do
      status { :failed }
    end

    trait :destroying do
      status { :destroying }
    end

    trait :with_projects do
      after(:create) do |cluster|
        create_list(:project, 3, cluster: cluster)
      end
    end

    trait :with_add_ons do
      after(:create) do |cluster|
        create_list(:add_on, 2, cluster: cluster)
      end
    end

    trait :with_metrics do
      after(:create) do |cluster|
        create_list(:metric, 5, cluster: cluster)
      end
    end
  end
end
