# Autogenerated by autotester

require 'rails_helper'

RSpec.describe CronSchedule, type: :model do
  describe 'associations' do
    it { is_expected.to belong_to(:service) }
  end

  describe 'validations' do
    it { is_expected.to validate_presence_of(:schedule) }
  end
end
