# Autogenerated by autotester

FactoryBot.define do
  factory :deployment do
    status { :in_progress }
    association :build

    trait :completed do
      status { :completed }
    end

    trait :failed do
      status { :failed }
    end

    after(:create) do |deployment|
      create(:log, loggable: deployment) if deployment.respond_to?(:log)
    end
  end
end
