# Autogenerated by autotester

FactoryBot.define do
  factory :domain do
    association :service

    sequence(:domain_name) { |n| "example#{n}.com" }
    status { :checking_dns }
    status_reason { "Initial status checking" }

    trait :dns_verified do
      status { :dns_verified }
      status_reason { "DNS successfully verified" }
    end

    trait :dns_incorrect do
      status { :dns_incorrect }
      status_reason { "DNS verification failed" }
    end

    trait :with_https_protocol do
      sequence(:domain_name) { |n| "https://example#{n}.com" }
    end

    trait :without_tld do
      sequence(:domain_name) { |n| "example#{n}" }
    end
  end
end
