# Autogenerated by autotester

require 'rails_helper'

FactoryBot.define do
  factory :event do
    event_action { :create }
    association :eventable, factory: :some_eventable_factory
    association :project
    association :user

    trait :update_action do
      event_action { :update }
    end

    trait :without_user do
      user { nil }
    end

    after(:build) do |event|
      # Ensure the eventable factory is set up correctly
      event.eventable ||= create(:some_eventable_factory)
    end
  end
end
