# Autogenerated by autotester

FactoryBot.define do
  factory :inbound_webhook do
    body { "Sample webhook body content" }
    status { :pending }

    trait :processing do
      status { :processing }
    end

    trait :processed do
      status { :processed }
    end

    trait :failed do
      status { :failed }
    end

    trait :with_sample_body do
      body { "Sample webhook body content with additional details" }
    end

    factory :processing_webhook, traits: [:processing]
    factory :processed_webhook, traits: [:processed]
    factory :failed_webhook, traits: [:failed]
  end
end
