# Autogenerated by autotester

# spec/factories/metrics.rb

FactoryBot.define do
  factory :metric do
    metadata { { "average" => rand(0.0..100.0), "peak" => rand(0.0..100.0) } }
    metric_type { Metric.metric_types.keys.sample }
    tags { ["namespace:#{Faker::Lorem.word}", "pod:#{Faker::Lorem.word}", "node:#{Faker::Lorem.word}"] }
    association :cluster

    trait :cpu_metric do
      metric_type { :cpu }
      metadata { { "average" => rand(0.0..100.0), "peak" => rand(0.0..100.0) } }
    end

    trait :memory_metric do
      metric_type { :memory }
      metadata { { "average" => rand(0.0..1024.0), "peak" => rand(0.0..1024.0) } }
    end

    trait :storage_metric do
      metric_type { :storage }
      metadata { { "average" => rand(0.0..1000.0), "peak" => rand(0.0..1000.0) } }
    end

    trait :with_node_only_tag do
      tags { ["node:#{Faker::Lorem.word}"] }
    end

    trait :for_specific_project do
      transient do
        project_name { "default_project" }
      end

      tags { ["namespace:#{project_name}", "pod:#{Faker::Lorem.word}"] }
    end
  end
end
