# Autogenerated by autotester

# spec/factories/project_add_ons.rb

FactoryBot.define do
  factory :project_add_on do
    association :project
    association :add_on

    trait :with_specific_project do
      association :project, factory: :specific_project
    end

    trait :with_specific_add_on do
      association :add_on, factory: :specific_add_on
    end
  end
end
