# Autogenerated by autotester

# spec/factories/projects.rb

FactoryBot.define do
  factory :project do
    sequence(:name) { |n| "project-#{n}" }
    autodeploy { true }
    branch { "main" }
    docker_build_context_directory { "." }
    dockerfile_path { "./Dockerfile" }
    repository_url { "owner/repository" }
    status { :creating }
    association :cluster

    trait :with_docker_command do
      docker_command { "bundle exec rails server" }
    end

    trait :with_predeploy_command do
      predeploy_command { "bundle exec rake db:migrate" }
    end

    trait :deployed do
      status { :deployed }
    end

    trait :destroying do
      status { :destroying }
    end

    after(:create) do |project|
      create_list(:service, 3, project: project)
      create_list(:build, 2, project: project)
      create_list(:event, 5, project: project)
    end
  end
end
