# Autogenerated by autotester

FactoryBot.define do
  factory :project_credential_provider do
    association :project
    association :provider

    trait :with_github_provider do
      after(:build) do |project_credential_provider|
        project_credential_provider.provider.auth = {
          "info" => {
            "nickname" => "github_user"
          }
        }.to_json
        project_credential_provider.provider.access_token = "ghp_exampleaccesstoken"
      end
    end

    trait :with_different_provider do
      after(:build) do |project_credential_provider|
        project_credential_provider.provider.auth = {
          "info" => {
            "nickname" => "other_user"
          }
        }.to_json
        project_credential_provider.provider.access_token = "other_exampleaccesstoken"
      end
    end
  end
end
