# Autogenerated by autotester

FactoryBot.define do
  factory :provider do
    association :user
    provider { "github" }
    uid { SecureRandom.uuid }
    access_token { SecureRandom.hex(20) }
    access_token_secret { SecureRandom.hex(20) }
    refresh_token { SecureRandom.hex(20) }
    auth { { some_auth_data: SecureRandom.hex(10) }.to_json }
    expires_at { 1.hour.from_now }

    trait :expired do
      expires_at { 1.hour.ago }
    end

    trait :facebook do
      provider { "facebook" }
      uid { SecureRandom.uuid }
    end

    trait :google do
      provider { "google" }
      uid { SecureRandom.uuid }
    end
  end
end
