# Autogenerated by autotester

require 'rails_helper'

FactoryBot.define do
  factory :service do
    association :project
    name { "example-service" }
    description { "A sample service description" }
    service_type { :web_service }
    status { :pending }
    container_port { 3000 }
    replicas { 1 }
    allow_public_networking { false }
    healthcheck_url { "http://example.com/health" }

    trait :web_service do
      service_type { :web_service }
      status { :healthy }
    end

    trait :background_service do
      service_type { :background_service }
      status { :pending }
    end

    trait :cron_job do
      service_type { :cron_job }
      command { "run-cron-job" }
      status { :pending }
      after(:build) do |service|
        service.cron_schedule ||= build(:cron_schedule, service: service)
      end
    end

    trait :healthy do
      status { :healthy }
    end

    trait :unhealthy do
      status { :unhealthy }
    end

    trait :updated do
      status { :updated }
    end

    factory :web_service, traits: [:web_service]
    factory :background_service, traits: [:background_service]
    factory :cron_job_service, traits: [:cron_job]
  end
end
