# Autogenerated by autotester

require 'rails_helper'

FactoryBot.define do
  factory :user do
    sequence(:email) { |n| "user#{n}@example.com" }
    password { 'password123' }
    first_name { 'John' }
    last_name { 'Doe' }
    admin { false }
    announcements_last_read_at { nil }
    remember_created_at { nil }
    reset_password_sent_at { nil }
    reset_password_token { nil }
    
    trait :admin do
      admin { true }
    end

    trait :with_avatar do
      after(:build) do |user|
        user.avatar.attach(
          io: File.open(Rails.root.join('spec', 'fixtures', 'files', 'avatar.jpg')),
          filename: 'avatar.jpg',
          content_type: 'image/jpeg'
        )
      end
    end

    trait :with_announcements_read do
      announcements_last_read_at { Time.current }
    end

    trait :with_reset_password do
      reset_password_sent_at { 2.days.ago }
      reset_password_token { SecureRandom.hex(10) }
    end
  end
end
