# FROM ruby:3.3
ARG RUBY_VERSION=3.3.4
FROM docker.io/library/ruby:$RUBY_VERSION-slim AS base

# Install dependencies for building Ruby
RUN apt-get update && apt-get install -y build-essential curl wget autoconf git

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    gnupg && \
    curl -k https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    rm -rf /var/lib/apt/lists/*

ARG NODE_VERSION=20.11.0
ARG YARN_VERSION=1.22.21
ENV BINDING="0.0.0.0" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="omit" \
    GEM_HOME="/usr/local/bundle"

RUN gem update --system && gem cleanup

# Install JavaScript dependencies
ENV PATH=/usr/local/node/bin:$PATH
RUN curl -sL https://github.com/nodenv/node-build/archive/master.tar.gz | tar xz -C /tmp/ && \
    /tmp/node-build-master/bin/node-build "${NODE_VERSION}" /usr/local/node && \
    npm install -g yarn@$YARN_VERSION && \
    rm -rf /tmp/node-build-master

# App dependencies
# Install necessary packages and setup kubectl and helm
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends ca-certificates imagemagick libvips libvips-dev libvips-tools poppler-utils libpq-dev postgresql-client && \
    update-ca-certificates && \
    curl -k -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -k -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl && \
    curl -k -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && \
    chmod +x get_helm.sh && \
    ./get_helm.sh && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt

# App
WORKDIR /rails

COPY ./Gemfile* ./.ruby-version /rails/
RUN bundle install --jobs $(nproc) --retry 5

COPY package.json yarn.lock /rails/
RUN yarn install

COPY . .

RUN gem install foreman

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD ["./bin/dev"]
