# Autogenerated by autotester

require 'rails_helper'

RSpec.describe Projects::BaseController, type: :controller do
  let(:user) { create(:user) }
  let(:account) { create(:account, owner: user) }
  let(:project) { create(:project, account: account) }

  before do
    sign_in user
    allow(controller).to receive(:current_account).and_return(account)
  end

  describe 'before_action :set_project' do
    context 'when project exists' do
      before do
        allow(controller).to receive(:params).and_return({ project_id: project.id })
        controller.send(:set_project)
      end

      it 'sets the @project instance variable' do
        expect(assigns(:project)).to eq(project)
      end
    end

    context 'when project does not exist' do
      it 'raises ActiveRecord::RecordNotFound error' do
        allow(controller).to receive(:params).and_return({ project_id: 'invalid_id' })
        
        expect { controller.send(:set_project) }.to raise_error(ActiveRecord::RecordNotFound)
      end
    end

    context 'when project belongs to another account' do
      let(:other_account) { create(:account) }
      let(:other_project) { create(:project, account: other_account) }

      it 'raises ActiveRecord::RecordNotFound error' do
        allow(controller).to receive(:params).and_return({ project_id: other_project.id })

        expect { controller.send(:set_project) }.to raise_error(ActiveRecord::RecordNotFound)
      end
    end
  end
end
