# Autogenerated by autotester

require 'rails_helper'

RSpec.describe Account, type: :model do
  let(:user) { create(:user) }
  let(:provider) { create(:provider, user:, auth: { info: { nickname: 'github_user' } }.to_json) }
  let(:account) { create(:account, owner: user) }
  describe '#github_username' do
    context 'when the owner has a github provider' do
      it 'returns the github username' do
        expect(account.github_username).to eq(JSON.parse(provider.auth)['info']['nickname'])
      end
    end

    context 'when the owner does not have a github provider' do
      it 'returns nil' do
        expect(account.github_username).to be_nil
      end
    end
  end

  describe '#github_access_token' do
    let(:account) { create(:account) }

    context 'when the owner has a github provider' do
      it 'returns the github access token' do
        expect(account.github_access_token).to eq(provider.access_token)
      end
    end

    context 'when the owner does not have a github provider' do
      it 'returns nil' do
        expect(account.github_access_token).to be_nil
      end
    end
  end
end
