# Autogenerated by autotester

require 'rails_helper'

RSpec.describe Announcement, type: :model do
  describe 'validations' do
    subject { build(:announcement) }

    it { is_expected.to validate_presence_of(:announcement_type) }
    it { is_expected.to validate_presence_of(:description) }
    it { is_expected.to validate_presence_of(:name) }
    it { is_expected.to validate_presence_of(:published_at) }

    it { is_expected.to validate_inclusion_of(:announcement_type).in_array(Announcement::TYPES) }
  end

  describe 'callbacks' do
    context 'after initialize' do
      it 'sets default values for announcement_type and published_at' do
        announcement = Announcement.new

        expect(announcement.announcement_type).to eq('new')
        expect(announcement.published_at).to be_within(1.second).of(Time.zone.now)
      end

      it 'retains provided values for announcement_type and published_at' do
        time = 2.days.ago
        announcement = Announcement.new(announcement_type: 'fix', published_at: time)

        expect(announcement.announcement_type).to eq('fix')
        expect(announcement.published_at).to eq(time)
      end
    end
  end
end
