# Autogenerated by autotester

require 'rails_helper'

RSpec.describe User, type: :model do
  describe 'callbacks' do
    describe 'before_save' do
      it 'downcases the email' do
        user = build(:user, email: 'USER@EXAMPLE.COM')
        user.save
        expect(user.reload.email).to eq('user@example.com')
      end
    end
  end

  describe 'readonly attributes' do
    it 'does not allow admin to be changed after creation' do
      user = create(:user)
      expect { user.update(admin: true) }.to raise_error(ActiveRecord::ReadOnlyRecord)
    end
  end

  describe 'instance methods' do
    describe '#github_provider' do
      let(:user) { create(:user) }
      let!(:github_provider) { create(:provider, user: user, provider: 'github') }
      let!(:other_provider) { create(:provider, user: user, provider: 'gitlab') }

      it 'returns the github provider if present' do
        expect(user.github_provider).to eq(github_provider)
      end

      it 'returns nil if github provider is not present' do
        github_provider.destroy
        expect(user.github_provider).to be_nil
      end
    end
  end
end
