# Autogenerated by autotester

require 'rails_helper'

RSpec.describe Services::Save, type: :action do
  describe '.executed' do
    let(:service) { instance_double('Service') }
    let(:context) { LightService::Context.make(service: service) }

    before do
      allow(service).to receive(:save!)
    end

    context 'when the service is valid' do
      it 'saves the service' do
        described_class.execute(context)
        expect(service).to have_received(:save!)
      end
    end

    context 'when the service is invalid' do
      before do
        allow(service).to receive(:save!).and_raise(ActiveRecord::RecordInvalid)
      end

      it 'raises an ActiveRecord::RecordInvalid error' do
        expect { described_class.execute(context) }.to raise_error(ActiveRecord::RecordInvalid)
      end
    end
  end
end
