# Autogenerated by autotester

require 'rails_helper'

RSpec.describe Clusters::BaseController, type: :controller do
  describe 'Callbacks' do
    it { is_expected.to use_before_action(:set_cluster) }
  end

  describe 'Private methods' do
    describe '#set_cluster' do
      let(:user) { create(:user) }
      let(:account) { create(:account, owner: user) }
      let(:cluster) { create(:cluster, account: account) }

      before do
        sign_in user
        allow(controller).to receive(:params).and_return({ cluster_id: cluster.id })
      end

      context 'when cluster exists' do
        it 'sets @cluster with the correct cluster' do
          controller.send(:set_cluster)
          expect(assigns(:cluster)).to eq(cluster)
        end
      end

      context 'when cluster does not exist' do
        before do
          allow(Cluster).to receive(:find).and_raise(ActiveRecord::RecordNotFound)
        end

        it 'raises an ActiveRecord::RecordNotFound error' do
          expect { controller.send(:set_cluster) }.to raise_error(ActiveRecord::RecordNotFound)
        end
      end
    end
  end
end
